version: '3'

services:
  app:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c "PORT=8080 yarn start"
    ports:
      - '8080:8080'
    tty: true
